# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'config.ru'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

AsciiComments:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lambda:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AccessorMethodName:
  Enabled: false

AndOr:
  Enabled: false

AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Metrics/PerceivedComplexity:
  Max: 8
