version: "2"
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: password
    image: postgres:9.6.1-alpine
    ports:
      - "5432:5432"
  webpack: &node
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    command: yarn run dev
    ports:
      - "3500:3500"
    volumes:
      - ./.eslintrc:/app/.eslintrc
      - ./client:/app/client
      - ./package.json:/app/package.json
      - ./public/assets:/app/public/assets
      - ./webpack.config.js:/app/webpack.config.js
      - ./yarn.lock:/app/yarn.lock
      - ./.flowconfig:/app/.flowconfig
      - ./flow-typed:/app/flow-typed
      - node_modules:/app/node_modules
  redis:
    image: redis:3.2.6-alpine
    ports:
      - "6379:6379"
  rails:
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    build:
      context: ./
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .rubocop.yml:/app/.rubocop.yml
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./config.ru:/app/config.ru
      - ./db:/app/db
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
      - ./lib:/app/lib
      - ./public:/app/public
      - ./Rakefile:/app/Rakefile
      - ./scripts:/app/scripts
      - ./log:/app/log
      - bundle:/bundle
      - ./tmp:/app/tmp
      - ./spec:/app/spec
      - .rspec:/app/.rspec
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    links:
      - postgres
      - redis
volumes:
  bundle:
  node_modules:
